vcare:
  version: 0.1.0
  aes-key: 'M)Fd*LYV+ABP'

spring:
  application:
    name: vcare
  profiles:
    active:
      - dev
  messages:
    basename: i18n/messages
    encoding: UTF-8
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false

server:
  port: 9090

logging:
  file:
    path: logs

jimmer:
  language: kotlin
  dialect: 'org.babyfish.jimmer.sql.dialect.PostgresDialect'
  show-sql: true
  pretty-sql: true
  database-validation-mode: error
  default-enum-strategy: ordinal
  executor-context-prefixes:
    - 'top.vcare'



sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: IsdfiSDDasddaFSSJIJddsafasdasASDS
  # 是否在初始化配置时打印版本字符画
  is-print: false